### PR TITLE
Style Changes for Headsup Dispatch

### PR DESCRIPTION
**Pull request by CKegel**
Changed style of info to all capital letters for clarity.
Before:
Before
After:
After

### CODE REVIEW

**Comment by ddbruce** [comment]
Add before and after screenshots to the PR please.

**Comment by CKegel** [comment]
Before and After pictures have been added

**Comment by lramos15** [comment]
This seems unnecessarily bold, especially given the rest of the UI is in normal casing. I understand maybe the determinant but does everything need to be caps?

**Comment by ddbruce** [comment]
https://en.wikipedia.org/wiki/All_caps#Readability

https://uxmovement.com/content/all-caps-hard-for-users-to-read/

> But when your message involves reading, don’t force users to read words with bad shape contrast.

**Comment by CKegel** [comment]
I spoke with the line side officers and the dev coordinator, they(and I) agree and I'm going to change it so each word is capitalized, with the determinant in uppercase. The reason they requested uppercase was to hide dispatch inconsistencies regarding RPI. Would you be opposed to adding some regex that replaced mis-cased versions of Rpi with RPI?

**Comment by CKegel** [comment]
Here is the new alert with the following input
Determinant:  "Charlie"
Complaint:  "Abdominal pain"
Location:  "Rpi - Sage Labs"
image

**Comment by lramos15** [comment]
> Would you be opposed to adding some regex that replaced mis-cased versions of Rpi with RPI?

No that seems fine

**Comment by CKegel** [comment]
> Looks fine, but let's take this time to clean up the code such that `#dispatch` is in the dispatch CSS file and not in both the light and dark mode files. It is the same CSS, right?

The code has been cleaned, it is the same css

**Review by ddbruce — APPROVED** [review]
lgtm, thanks @CKegel!

**Pull request merged**
